### PR TITLE
Update boost pin

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender.

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender.

**Comment by jschueller** [comment]
@conda-forge-admin, please rerender

**Comment by jschueller** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Guess it was re-rendered enough. Will see how this goes.

**Pull request merged**
